#pragma once
#include <algorithm>
#include <array>
#include <string_view>

// This file contains lists of directories, extensions, filenames, and paths to be skipped during scanning.
// These are all defined as constexpr arrays of string_views for efficiency
// i.e, they are resolved at compile time and stored in read-only memory.
// They are sorted for binary search - and are all lowercase for case-insensitive comparison.
// This is verified through static_asserts also resolved at compile time.

using namespace std::string_view_literals;

static constexpr std::array skipped_directories{
	L".git"sv,
	L".vs"sv,
	L".vscode"sv,
};
static_assert(std::ranges::is_sorted(skipped_directories));

// not case-sensitive so can be mem-compared, and thus sorted for binary search
static constexpr std::array skipped_extensions{
	L""sv,
	L".1"sv,
	L".2"sv,
	L".a"sv,
	L".ace"sv,
	L".acp"sv,
	L".akm"sv,
	L".aml"sv,
	L".ani"sv,
	L".ans"sv,
	L".appx"sv,
	L".appxbundle"sv,
	L".appxupload"sv,
	L".aps"sv,
	L".asf"sv,
	L".asm"sv,
	L".asset"sv,
	L".avi"sv,
	L".bak"sv,
	L".bat"sv,
	L".bc"sv,
	L".bcd_"sv,
	L".bin"sv,
	L".bla"sv,
	L".blg"sv,
	L".bmf"sv,
	L".bmp"sv,
	L".bmpx"sv,
	L".bmq"sv,
	L".bootmgr"sv,
	L".br"sv,
	L".bsl"sv,
	L".cab"sv,
	L".cabinet"sv,
	L".cache"sv,
	L".cap"sv,
	L".cat"sv,
	L".cbs"sv,
	L".cd"sv,
	L".cdf-ms"sv,
	L".cer"sv,
	L".cfg"sv,
	L".chm"sv,
	L".cip"sv,
	L".class"sv,
	L".clg"sv,
	L".cmd"sv,
	L".com"sv,
	L".core"sv,
	L".crt"sv,
	L".cso"sv,
	L".cur"sv,
	L".d"sv,
	L".dat"sv,
	L".data"sv,
	L".db"sv,
	L".dbf"sv,
	L".dbmdl"sv,
	L".dds"sv,
	L".def"sv,
	L".der"sv,
	L".devicemetadata-ms"sv,
	L".diagcab"sv,
	L".dic"sv,
	L".djt"sv,
	L".djx"sv,
	L".dll"sv,
	L".dll_"sv,
	L".dls"sv,
	L".dmp"sv,
	L".do_"sv,
	L".doc"sv,
	L".doc_"sv,
	L".docm"sv,
	L".docx"sv,
	L".dot"sv,
	L".dotsettings"sv,
	L".dpk"sv,
	L".dub"sv,
	L".efi"sv,
	L".emf"sv,
	L".eny"sv,
	L".eot"sv,
	L".esd"sv,
	L".etl"sv,
	L".evf"sv,
	L".evtx"sv,
	L".exe"sv,
	L".exe_"sv,
	L".exp"sv,
	L".fd"sv,
	L".ffu"sv,
	L".fig"sv,
	L".fil"sv,
	L".fnt"sv,
	L".foo"sv,
	L".fpie"sv,
	L".frx"sv,
	L".fv"sv,
	L".g4"sv,
	L".gif"sv,
	L".good"sv,
	L".grl"sv,
	L".guiskin"sv,
	L".gz"sv,
	L".hds"sv,
	L".hiv"sv,
	L".hlp"sv,
	L".hrl"sv,
	L".htm"sv,
	L".html"sv,
	L".iab"sv,
	L".iad"sv,
	L".ibd"sv,
	L".ico"sv,
	L".ilk"sv,
	L".imaginghelper"sv,
	L".imb"sv,
	L".imd"sv,
	L".in"sv,
	L".inc"sv,
	L".inf"sv,
	L".inx"sv,
	L".iobj"sv,
	L".ipch"sv,
	L".ipynb"sv,
	L".ism"sv,
	L".isma"sv,
	L".ismv"sv,
	L".iso"sv,
	L".jar"sv,
	L".jcc"sv,
	L".jpeg"sv,
	L".jpg"sv,
	L".json"sv,
	L".jxr"sv,
	L".kar"sv,
	L".keys"sv,
	L".kor"sv,
	L".lang-de-de"sv,
	L".ldf"sv,
	L".lex"sv,
	L".lib"sv,
	L".lic"sv,
	L".lm"sv,
	L".lm1"sv,
	L".lm2"sv,
	L".lm3"sv,
	L".lm4"sv,
	L".lm5"sv,
	L".lnk"sv,
	L".lzma"sv,
	L".m4a"sv,
	L".man"sv,
	L".mars"sv,
	L".mat"sv,
	L".mbt"sv,
	L".mcp"sv,
	L".md"sv,
	L".mdb"sv,
	L".mdf"sv,
	L".mdp"sv,
	L".mdxml"sv,
	L".metadata_dll"sv,
	L".mfl"sv,
	L".mflt"sv,
	L".mht"sv,
	L".mid"sv,
	L".mix"sv,
	L".mkv"sv,
	L".mof"sv,
	L".mp"sv,
	L".mp3"sv,
	L".mp4"sv,
	L".mpp"sv,
	L".mpt"sv,
	L".msc"sv,
	L".msi"sv,
	L".mst"sv,
	L".msu"sv,
	L".mui"sv,
	L".mum"sv,
	L".n12"sv,
	L".nin"sv,
	L".nlp"sv,
	L".nls"sv,
	L".nlt"sv,
	L".nlx"sv,
	L".nsh"sv,
	L".ntl"sv,
	L".num2"sv,
	L".num3"sv,
	L".nupkg"sv,
	L".o"sv,
	L".obj"sv,
	L".ogg"sv,
	L".old"sv,
	L".one"sv,
	L".onnx"sv,
	L".opt"sv,
	L".out"sv,
	L".p12"sv,
	L".p7"sv,
	L".p7b"sv,
	L".p7x"sv,
	L".package"sv,
	L".pass1"sv,
	L".pass2"sv,
	L".patch"sv,
	L".pbit"sv,
	L".pbix"sv,
	L".pch"sv,
	L".pchast"sv,
	L".pck"sv,
	L".pdb"sv,
	L".pdf"sv,
	L".pdn"sv,
	L".pfi"sv,
	L".pfx"sv,
	L".physicsmaterial2d"sv,
	L".pl"sv,
	L".pm"sv,
	L".png"sv,
	L".pngx"sv,
	L".po"sv,
	L".pow"sv,
	L".ppt"sv,
	L".pptx"sv,
	L".pr"sv,
	L".prefab"sv,
	L".pri"sv,
	L".private_dll"sv,
	L".ps"sv,
	L".ps1"sv,
	L".psd1"sv,
	L".psf"sv,
	L".psm1"sv,
	L".pvk"sv,
	L".pya"sv,
	L".pyc"sv,
	L".pyv"sv,
	L".qfg"sv,
	L".r"sv,
	L".rat"sv,
	L".raw"sv,
	L".rcpp"sv,
	L".reg"sv,
	L".removeext"sv,
	L".renametozip"sv,
	L".res"sv,
	L".resources"sv,
	L".resw"sv,
	L".rlib"sv,
	L".rmeta"sv,
	L".rtf"sv,
	L".scc"sv,
	L".sdb"sv,
	L".sdc"sv,
	L".sdf"sv,
	L".sdi"sv,
	L".sdi_"sv,
	L".shp"sv,
	L".shx"sv,
	L".sim"sv,
	L".snk"sv,
	L".spd"sv,
	L".spkg"sv,
	L".sqlite3"sv,
	L".ss"sv,
	L".sst"sv,
	L".stl"sv,
	L".suo"sv,
	L".svg"sv,
	L".swp"sv,
	L".sym"sv,
	L".sys"sv,
	L".table"sv,
	L".testhelper"sv,
	L".tif"sv,
	L".tiff"sv,
	L".tlb"sv,
	L".tlv"sv,
	L".tmp"sv,
	L".trc"sv,
	L".ts"sv,
	L".ttf"sv,
	L".txt"sv,
	L".uni"sv,
	L".unity"sv,
	L".vbs"sv,
	L".vf"sv,
	L".vfd"sv,
	L".vhd"sv,
	L".vhdx"sv,
	L".vmcx"sv,
	L".vmrs"sv,
	L".vol"sv,
	L".vsd"sv,
	L".vsdm"sv,
	L".vsdx"sv,
	L".vsix"sv,
	L".vss"sv,
	L".vtg"sv,
	L".vti"sv,
	L".wav"sv,
	L".wew"sv,
	L".wfw"sv,
	L".wim"sv,
	L".winmd"sv,
	L".wk3"sv,
	L".wla57"sv,
	L".wma"sv,
	L".wmf"sv,
	L".wmp"sv,
	L".wmv"sv,
	L".woff"sv,
	L".woff2"sv,
	L".wprp"sv,
	L".wsf"sv,
	L".xbf"sv,
	L".xla"sv,
	L".xls"sv,
	L".xlsx"sv,
	L".xlsx_"sv,
	L".xpr"sv,
	L".xsd"sv,
	L".xsl"sv,
	L".xsn"sv,
	L".xtc"sv,
	L".yuvx"sv,
	L".zip"sv,
};
static_assert(std::ranges::is_sorted(skipped_extensions));

static constexpr std::array skipped_filenames{
	L".clang-format"sv,
	L".editorconfig"sv,
	L".gitignore"sv,
	L"_readme_first"sv,
	L"bcd_"sv,
	L"bcd_overlaylevel_3"sv,
	L"bootstat"sv,
	L"builder.resources"sv,
	L"charprops-bmp"sv,
	L"createfileincontext"sv,
	L"dirs"sv,
	L"drivers"sv,
	L"invalidsymlinkhive"sv,
	L"lastknown"sv,
	L"makefile"sv,
	L"mp3enc.lib.bak"sv,
	L"mylock"sv,
	L"nofile"sv,
	L"output"sv,
	L"pagefile"sv,
	L"rca09728"sv,
	L"rca22620"sv,
	L"rca29348"sv,
	L"rca36688"sv,
	L"rca45952"sv,
	L"rca88212"sv,
	L"readme"sv,
	L"resources.resources"sv,
	L"rsa32k.w"sv,
	L"samempty"sv,
	L"sampassword"sv,
	L"sampletest"sv,
	L"scratch"sv,
	L"software"sv,
	L"sources"sv,
	L"stub512.w"sv,
	L"system"sv,
	L"system-empty"sv,
	L"system-no-wpa"sv,
	L"testsignature_bad"sv,
	L"testsignature_good"sv,
	L"verifyfile"sv,
};
static_assert(std::ranges::is_sorted(skipped_filenames));

static constexpr std::array skipped_paths{
	// under /minkernel/
	L".\\boot\\environ\\app\\pwboot"sv,
	L".\\boot\\firmware\\intel\\pinolem\\afu"sv,
	L".\\boot\\firmware\\woa\\ti\\vegas2"sv,
	
	// under /onecore/base/
	L".\\cbs\\unittests\\ref\\rebaseph\\negativemultiplepackages"sv,
	L".\\ci\\test\\upolicymgmt\\testdata"sv,

	// under /onecore/base/
	L".\\compress\\msdelta2\\unittests\\api\\data\\set1"sv,
	L".\\compress\\msdelta2\\unittests\\api\\data\\set2"sv,
	L".\\compress\\msdelta\\bugs\\1"sv,
	L".\\compress\\msdelta\\scripts"sv,

	// under /minkernel/
	L".\\devices\\devfilter\\fuzztest\\grammartest\\seeds"sv,

	// under /base/
	L".\\fs\\test\\nfs\\server\\cattests\\unixutils"sv,
	L".\\fs\\test\\nfs\\server\\xrttests\\unixutils"sv,

	// under /minkernel/
	L".\\ium\\tests\\iumtests\\hpstress\\res"sv,

	// under /onecore/base/
	L".\\ngscb\\cornerstone\\tests\\helperlib\\testdata"sv,
	L".\\ngscb\\hassrv\\tcglogparser\\functionaltests\\data"sv,
	L".\\ngscb\\internaltools\\tbsloggenerator\\test\\logs"sv,
	L".\\ngscb\\tpm\\vtpm\\win32um\\fuzzing\\fuzzer\\vtpminitfuzzer\\corpus"sv,

	// under /minkernel/
	L".\\ntos\\rtl\\test_lz4"sv,

	// under /base/
	L".\\ntsetup\\migration\\migcore\\testplatform\\common\\main"sv,
	L".\\ntsetup\\migration\\migcore\\testplatform\\x86\\main"sv,
	L".\\ntsetup\\migshared\\migutil\\test\\data"sv,

	// under /base/
	L".\\ptp\\provision\\bepa\\bootos"sv,

	// under /onecore/base/
	L".\\servicing\\unittests\\packages\\offlinetests\\overlappingcomponents"sv,

	// under /net/
	L".\\test\\winsock\\stress\\sockdie\\server\\txfiles"sv,

	// under /minkernel/
	L".\\tests\\ucrt\\crtlibc\\test\\clib\\libauto\\data"sv,
	L".\\tests\\ucrt\\crtlibc\\test\\clib\\safeint\\arith_u_op_safeint_t"sv,

	// under /onecoreuap/base
	L".\\tools\\wdtf\\testrunner"sv,
	L".\\tools\\wdtf_package_tests\\dplat\\util\\pnp_datagatherer_test\\vm_baseline_dell\\baseline"sv,
	L".\\tools\\wdtf_package_tests\\dplat\\util\\pnp_deviceinterface_test\\vm_baseline_dell\\baseline"sv,

	// under /onecore/base/
	L".\\wcp\\unittests\\data\\com_store"sv,
	L".\\wcp\\unittests\\data\\pcmc_test"sv,
	L".\\wcp\\unittests\\data\\xml"sv,
};
static_assert(std::ranges::is_sorted(skipped_paths));

static constexpr std::array skipped_path_prefixes{
	// under /onecore/base/
	L".\\cbs\\mobile\\unittests\\packages\\"sv,
	L".\\cbs\\tests\\data\\driverservicing\\"sv,
	L".\\cbs\\tests\\data\\packages\\"sv,
	L".\\cbs\\tests\\data\\sessionservicing\\mpp_withcriticaldoq_poq"sv,
	L".\\cbs\\unittests\\packages\\"sv,

	// under /onecore/base/
	L".\\compress\\msdelta2\\UnitTests\\api\\data\\"sv,

	// under /base/
	L".\\fs\\test\\cmdlineutilities\\robocopy\\out\\"sv,

	// under /onecore/base/
	L".\\servicing\\test\\testinput\\data\\"sv,
	L".\\servicing\\unittests\\packages\\cimrecipetest"sv,

	// under /onecore/base/
	L".\\wcp\\unittests\\data\\com_store\\"sv,
};
static_assert(std::ranges::is_sorted(skipped_path_prefixes));

static constexpr std::array extensions_to_fix_form_feed{
	L".c"sv,
	L".cpp"sv,
	L".cxx"sv,
	L".h"sv,
	L".hpp"sv,
	L".hxx"sv,
	L".idl"sv,
	L".mc"sv,
	L".rc"sv,
	L".w"sv,
};
static_assert(std::ranges::is_sorted(extensions_to_fix_form_feed));
